title: Mayank Vikash
description: This site is built with Jelyll and is maintained by Mayank Vikash.
author: Mayank Vikash

show_downloads: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
